import { useCallback, useEffect, useState } from 'react';
import { summary, Summary } from '../api';
import { shortBlob } from '../chat';
import { Button, PrintIcon, ScopeBadge, isDemoNamespace } from '../ui';
import './PrintView.css';

/**
 * Emergency card — allergies, meds, routines, contacts, each line traceable
 * to its blob. Paper styles live in PrintView.css; the blob cites must never
 * be hidden when printed.
 */
export default function PrintView({ user }: { user: string }) {
  const [data, setData] = useState<Summary | null>(null);
  const [failed, setFailed] = useState(false);

  const load = useCallback(async () => {
    setFailed(false);
    try {
      setData(await summary(user));
    } catch {
      setData(null);
      setFailed(true);
    }
  }, [user]);

  useEffect(() => {
    load();
  }, [load]);

  const sections: { label: string; items: { text: string; blobId?: string | null }[] }[] =
    [];
  if (data) {
    if (data.allergies?.length) sections.push({ label: 'Allergies', items: data.allergies });
    if (data.medications?.length)
      sections.push({ label: 'Medications', items: data.medications });
    if (data.routine?.length) sections.push({ label: 'Routine', items: data.routine });
    if (data.contacts?.length) sections.push({ label: 'Care contacts', items: data.contacts });
    for (const s of data.sections ?? []) {
      if (s.items?.length) sections.push(s);
    }
  }

  return (
    <div className="print-wrap">
      <div className="print-actions">
        <p className="view-note">
          <ScopeBadge user={user} />{' '}
          {isDemoNamespace(user)
            ? 'Premade shared profile — nothing here is yours.'
            : 'Only your own care record is shown here.'}{' '}
          A paper-safe card for the fridge or the doctor's visit — compiled
          from recall only, every line cited.
        </p>
        <Button variant="primary" onClick={() => window.print()}>
          <PrintIcon /> Print
        </Button>
      </div>

      {failed && (
        <div className="view-empty" role="status">
          The summary couldn't be compiled right now.
        </div>
      )}

      {data && (
        <article className="pr-card">
          <header className="pr-head">
            <h2>Emergency care card</h2>
            <span className="pr-user">{data.user}</span>
          </header>

          {sections.length === 0 && (
            <p className="pr-empty">Nothing remembered yet for this person.</p>
          )}

          {sections.map((s) => (
            <section key={s.label} className="pr-section">
              <h3>{s.label}</h3>
              <ul>
                {s.items.map((it, i) => (
                  <li key={i}>
                    <span>{it.text}</span>
                    {it.blobId && <code className="pr-blobids">{shortBlob(it.blobId)}</code>}
                  </li>
                ))}
              </ul>
            </section>
          ))}

          <footer className="pr-foot">
            Confirm with your doctor — this is not medical advice. Generated by
            Mediara from verifiable memory receipts.
          </footer>
        </article>
      )}
    </div>
  );
}
